version: 2
jobs:
  build:
    working_directory: ~/pbson
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.1
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt python-pip git
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Test
          command: cat /dev/null | sbt clean coverage test coverageReport && sbt coverageAggregate && sbt coveralls
      - run:
          name: Compile dist package
          command: cat /dev/null | sbt clean update compile publish
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run: curl -fL https://getcli.jfrog.io | sh
      - deploy:
          command: |
            ./jfrog rt config --url https://dl.bintray.com/evgenekiiski/pbson --user evgenekiiski --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt u repository pbson --build-name=name_$CIRCLE_BUILD_NUM --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce name_$CIRCLE_BUILD_NUM $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp name_$CIRCLE_BUILD_NUM $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory