version: 2
jobs:
  test:
    working_directory: ~/pbson
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.1
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt python-pip git
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Test
          command: cat /dev/null | sbt clean coverage test coverageReport && sbt coverageAggregate && sbt coveralls
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  publish:
    working_directory: ~/pbson
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.1
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt python-pip git
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile dist package
          command: cat /dev/null | sbt clean update compile publish
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - run: curl -fL https://getcli.jfrog.io | sh
      - deploy:
          command: |
            ./jfrog bt config --user evgenekiiski --key $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog bt u repository/ twistedlogic/pbson/pbson/$CIRCLE_TAG /ru/twistedlogic/pbson_2.12/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
#      - publish:
#          requires:
#            - test
#          filters:
#            branches:
#              only:
#                - master
#            tags:
#              only: /^v.*/